[GLOBAL]
pants_version = "2.11.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.typecheck.mypy",
]

[source]
root_patterns = [
  'src',
]

[python]
interpreter_constraints = ["CPython==3.9.*"]

[flake8]
config = ".flake8"

[anonymous-telemetry]
enabled = false
