name: Build And Push
on:
  push:
    branches:
      - master

jobs:
  preview:
    name: Build And Push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
        uses: docker/setup-buildx-action@v2
      - run: |
          ./pants package ::
          docker build -t singer .
          docker run --rm -it singer singer_bins.tap_github/pex__tap_github.pex 
